# ansible-playbook --private-key=~/.minishift/machines/minishift/id_rsa --u docker -i `minishift ip`, minishift.yaml
#

- hosts: localhost
  tasks:
  # ansible-playbook minishift.yaml --tags=minishift
  - name: minishift
    tags: [minishift]
    shell:
      cmd: |
        minishift delete --clear-cache --force && rm -rf ~/.minishift ~/.kube/* && \
        minishift start --memory=12Gb && \
        minishift addons apply anyuid && \
        minishift addons apply admin-user && \
        oc login -u system:admin && \
        minishift console

- hosts: all
  become: true
  tasks:
  - name: Permissive selinux
    command: setenforce 0
  - name: Persistent Volume root
    file:
      path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv
      state: directory
  - name: Persistent Volume quay-postgres
    file:
      path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/quay-postgres
      state: directory
      mode: 0777
  - name: Persistent Volume quay-redis
    file:
      path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/quay-redis
      state: directory
      mode: 0777

- hosts: localhost
  tasks:
  - name: Check for project 'quay-enterprise'
    command: oc get projects -o jsonpath='{.items[?(.metadata.name=="quay-enterprise")].metadata.name}'
    register: result
  - name: Create project 'quay-enterprise' if doesn't exist
    command: oc new-project quay-enterprise
    when: result.stdout != "quay-enterprise"

  - name: Check for PV 'quay-postgres'
    command: oc get pv -n quay-enterprise -o jsonpath='{.items[?(.metadata.name=="quay-postgres")].metadata.name}'
    register: result
  - name: Create PV 'quay-postgres'
    when: result.stdout != "quay-postgres"
    shell:
      cmd: |
        cat <<EOF | oc create -n quay-enterprise -f -
        kind: PersistentVolume
        apiVersion: v1
        metadata:
          name: quay-postgres
        spec:
          capacity:
            storage: 1Gi
          accessModes:
            - ReadWriteOnce
          storageClassName: slow
          hostPath:
            path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/quay-postgres
        EOF

  - name: Check for PV 'quay-redis'
    command: oc get pv -n quay-enterprise -o jsonpath='{.items[?(.metadata.name=="quay-redis")].metadata.name}'
    register: result
  - name: Create PV 'quay-redis'
    when: result.stdout != "quay-redis"
    shell:
      cmd: |
        cat <<EOF | oc create -n quay-enterprise -f -
        kind: PersistentVolume
        apiVersion: v1
        metadata:
          name: quay-redis
        spec:
          capacity:
            storage: 1Gi
          accessModes:
            - ReadWriteOnce
          storageClassName: slow
          hostPath:
            path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/quay-redis
        EOF

  - name: Import redis image
    command: oc import-image openshift/redis:32 --from=registry.access.redhat.com/rhscl/redis-32-rhel7 -n quay-enterprise --confirm -n quay-enterprise

  - name: Check for Template 'postgresql-persistent'
    command: oc get template -n quay-enterprise -o jsonpath='{.items[?(.metadata.name=="postgresql-persistent")].metadata.name}'
    register: result
  - name: Create Template 'postgresql-persistent'
    when: result.stdout != "postgresql-persistent"
    command: oc create -n quay-enterprise -f https://raw.githubusercontent.com/openshift/origin/master/examples/db-templates/postgresql-persistent-template.json

  - name: Check for DeploymentConfig 'quay-postgres'
    command: oc get dc -n quay-enterprise -o jsonpath='{.items[?(.metadata.name=="quay-postgres")].metadata.name}'
    register: result
  - name: Process Template 'postgresql-persistent'
    when: result.stdout != "quay-postgres"
    shell:
      cmd: |
        oc process postgresql-persistent \
               -p POSTGRESQL_USER=quay \
               -p POSTGRESQL_PASSWORD=quay \
               -p POSTGRESQL_DATABASE=quay \
               -p VOLUME_CAPACITY=1Gi \
               -p DATABASE_SERVICE_NAME=quay-postgres \
               -p MEMORY_LIMIT=512Mi \
           | oc create -n quay-enterprise -f -
  - name: Remove non-backed PVC 'quay-postgres'
    when: result.stdout != "quay-postgres"
    command: oc delete pvc -n quay-enterprise quay-postgres
  - name: Create PVC 'quay-postgres'
    when: result.stdout != "quay-postgres"
    shell:
      cmd: |
        cat <<EOF | oc create -n quay-enterprise -f -
        kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: quay-postgres
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: slow
          selector:
            name: quay-postgres
        EOF


  - name: Check for Template 'redis-persistent'
    command: oc get template -n quay-enterprise -o jsonpath='{.items[?(.metadata.name=="redis-persistent")].metadata.name}'
    register: result
  - name: Create Template 'redis-persistent'
    when: result.stdout != "redis-persistent"
    command: oc create -n quay-enterprise -f https://raw.githubusercontent.com/openshift/origin/master/examples/db-templates/redis-persistent-template.json

  - name: Check for DeploymentConfig 'quay-redis'
    command: oc get dc -n quay-enterprise -o jsonpath='{.items[?(.metadata.name=="quay-redis")].metadata.name}'
    register: result
  - name: Process Template 'redis-persistent'
    when: result.stdout != "quay-redis"
    shell:
      cmd: |
        oc process redis-persistent \
               -p REDIS_PASSWORD=quay \
               -p VOLUME_CAPACITY=1Gi \
               -p DATABASE_SERVICE_NAME=quay-redis \
               -p MEMORY_LIMIT=512Mi \
           | oc create -n quay-enterprise -f -
  - name: Remove non-backed PVC 'quay-redis'
    when: result.stdout != "quay-redis"
    command: oc delete pvc -n quay-enterprise quay-redis
  - name: Create PVC 'quay-redis'
    when: result.stdout != "quay-redis"
    shell:
      cmd: |
        cat <<EOF | oc create -n quay-enterprise -f -
        kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: quay-redis
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: slow
          selector:
            name: quay-redis
        EOF

  - name: Check for Secret 'quay-enterprise-config-secret'
    command: oc get secrets -n quay-enterprise -o jsonpath='{.items[?(.metadata.name=="quay-enterprise-config-secret")].metadata.name}'
    register: result
  - name: Create Secret 'quay-enterprise-config-secret'
    when: result.stdout != "quay-enterprise-config-secret"
    shell:
      cmd: |
        cat <<EOF | oc create -n quay-enterprise -f -
        apiVersion: v1
        kind: Secret
        metadata:
          name: quay-enterprise-config-secret
        EOF

  - name: Check for Secret 'quay-dockerconfig'
    command: oc get secrets -n quay-enterprise -o jsonpath='{.items[?(.metadata.name=="quay-dockerconfig")].metadata.name}'
    register: result
  - name: Create Secret 'quay-dockerconfig'
    when: result.stdout != "quay-dockerconfig"
    shell:
      cmd: |
        oc create secret generic quay-dockerconfig --from-file=.dockerconfigjson=/home/thomasmckay/.docker/config.json --type=kubernetes.io/dockerconfigjson -n quay-enterprise
        oc secrets link default quay-dockerconfig --for=pull -n quay-enterprise
        oc secrets link deployer quay-dockerconfig -n quay-enterprise

  #oc import-image openshift/quay:rhel7 --from=quay.io/thomasmckay/quay:rhel7 -n quay-enterprise --confirm
