# ansible-playbook -i "devel.example.com," -e ansible_python_interpreter=/home/vagrant/code/operators/quay-operator/.venv/bin/python "$@" /dev/stdin <<EOF
# - hosts: devel.example.com
#   become: vagrant
#   vars:
#     quay_image: quay.io/redhat/quay:v3.0.1
#     clair_image: quay.io/redhat/clair-jwt:v3.0.1
#     build_image: quay.io/redhat/quay-builder:v3.0.1
#   tasks:
#     - include: `pwd`/roles/local-teardown.yaml
# EOF
---
- name: Tear down setup
  tags: [teardown, full-setup]
  ignore_errors: yes
  shell:
    cmd: |
      docker kill quay-postgresql quay-redis quay-config quay clair-postgresql clair
      rm -Rf ~/quay-postgresql ~/quay-config ~/quay-redis ~/quay-storage ~/clair-config ~/clair-postgresql
      rm -f /tmp/quay/*
