---
- name: Quay Postgresql container
  docker_container:
    name: quay-postgresql
    image: registry.redhat.io/rhscl/postgresql-96-rhel7:latest
    volumes:
      - ~/quay-postgresql:/var/lib/postgresql/data/pgdata:Z
    env:
      POSTGRESQL_USER: quay
      POSTGRESQL_PASSWORD: quay
      POSTGRESQL_DATABASE: quay
    ports:
      - "5432:5432"
    etc_hosts:
      thomasmckay-desktop.usersys.redhat.com: 192.168.1.2
    keep_volumes: false
    auto_remove: true
    state: started
- name: Postgresql add pg_trgm extension
  shell:
    cmd: |
      docker exec quay-postgresql bash -l -c 'echo "CREATE EXTENSION pg_trgm" | psql quay'
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
