---
- name: Quay Redis container
  docker_container:
    name: quay-redis
    image: registry.redhat.io/rhscl/redis-32-rhel7:latest
    volumes:
      - ~/quay-redis:/var/lib/redis:Z
    ports:
      - "6379:6379"
    keep_volumes: false
    auto_remove: true
    state: started
