---
- name: Create clair.yaml
  vars:
    quay_endpoint: 192.168.1.2
    clair_endpoint: 192.168.1.2
    key_id: 0117333c026c00d4ee8138182cbe100b0e4504b05315888af8f7d80fbeae4da7
  shell:
    cmd: |
      # cp /tmp/quay/clair.cert ~/clair-config/clair.cert
      # cp /tmp/quay/clair.key ~/clair-config/clair.key
      cp /tmp/quay/single.cert ~/clair-config/clair.cert
      cp /tmp/quay/single.key ~/clair-config/clair.key
      cat <<EOF > ~/clair-config/config.yaml
      clair:
        database:
          type: pgsql
          options:
            source: postgresql://quay:quay@{{ clair_endpoint }}:5432/clair?sslmode=disable
            cachesize: 16384
        api:
          healthport: 6061
          port: 6062
          timeout: 900s
          paginationkey: "XxoPtCUzrUv4JV5dS+yQ+MdW7yLEJnRMwigVY/bpgtQ="
        updater:
          interval: 6h
          enabledupdaters:
          - rhel
          - alpine
          notifier:
            attempts: 3
            renotifyinterval: 1h
            http:
              endpoint: https://{{ quay_endpoint }}/secscan/notify
              proxy: http://localhost:6063
      jwtproxy:
        signer_proxy:
          enabled: true
          listen_addr: :6063
          ca_key_file: /certificates/mitm.key
          ca_crt_file: /certificates/mitm.crt
          signer:
            issuer: security_scanner
            expiration_time: 5m
            max_skew: 1m
            nonce_length: 32
            private_key:
              type: preshared
              options:
                key_id: {{ key_id }}
                private_key_path: /clair/config/security_scanner.pem
        verifier_proxies:
        - enabled: true
          listen_addr: :6060
          key_file: /clair/config/clair.key
          crt_file: /clair/config/clair.cert
          verifier:
            audience: https://{{ clair_endpoint }}:6060
            upstream: http://localhost:6062
            key_server:
              type: keyregistry
              options:
                registry: https://{{ quay_endpoint }}/keys/
      EOF

- name: Pull latest image
  shell:
    cmd: |
      docker pull quay.io/thomasmckay/clair-jwt:rhel7


- name: Clair Postgresql container
  docker_container:
    name: clair
    image: quay.io/thomasmckay/clair-jwt:rhel7
    volumes:
      - ~/clair-config:/clair/config:Z
      - /tmp/quay/single.cert:/etc/pki/ca-trust/source/anchors/ca.crt
      # - /tmp/quay/clair.cert:/etc/pki/ca-trust/source/anchors/clair.crt
      # - /tmp/quay/rootCA.pem:/etc/pki/ca-trust/source/anchors/ca.crt
      #- ~/clair-config/config.yaml:/config/config.yaml
      #- ~/clair-config:/clair/config:Z
      # - /tmp/quay/clair.cert:/usr/local/share/ca-certificates/ca.crt
    ports:
      - "6060:6060"
      - "6061:6061"
    keep_volumes: false
    auto_remove: true
    state: started
    restart: true
  register: result
  until: result is succeeded
  retries: 5
  delay: 10