

docker run --rm -it -e SERVER=wss://thomasmckay-desktop.usersys.redhat.com -v /home/thomasmckay/quay-builder:/certs -v /var/run/docker.sock:/var/run/docker.sock:Z --add-host thomasmckay-desktop.usersys.redhat.com:192.168.1.2 --network host quay.io/thomasmckay/quay-builder:rhel7