---
- name: "PersistentVolume {{ name }}"
  k8s:
    state: present
    definition:
      kind: PersistentVolume
      apiVersion: v1
      metadata:
        name: "{{ name }}"
        namespace: "{{ namespace }}"
      spec:
        capacity:
          storage: 1Gi
        accessModes:
          - ReadWriteOnce
        storageClassName: slow
        hostPath:
          path: "/mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/{{ name }}"

