---
- name: Permissive selinux
  command: setenforce 0
- name: Persistent Volume root
  file:
    path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv
    state: directory
- name: Persistent Volume quay-postgres
  file:
    path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/quay-postgres
    state: directory
    mode: 0777
- name: Persistent Volume quay-redis
  file:
    path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/quay-redis
    state: directory
    mode: 0777
- name: Persistent Volume clair-postgres
  tags: [clair]
  file:
    path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/clair-postgres
    state: directory
    mode: 0777
- name: Fetch minishift ca.crt
  tags: [tls]
  fetch:
    src: /var/lib/minishift/base/openshift-apiserver/ca.crt
    dest: tmp/minishift.crt
    flat: yes
- name: Fetch minishift ca.key
  tags: [tls]
  fetch:
    src: /var/lib/minishift/base/openshift-apiserver/ca.key
    dest: tmp/minishift.key
    flat: yes
- name: Fetch minishift ca.serial.txt
  tags: [tls]
  fetch:
    src: /var/lib/minishift/base/openshift-apiserver/ca.serial.txt
    dest: tmp/minishift.serial.txt
    flat: yes
