---
- name: "Check for PVC '{{ name }}'"
  shell:
    cmd: "oc get pvc -n {{ namespace }} | grep {{ name }}"
  register: result
- name: "Remove non-backed PVC '{{ name }}'"
  command: "oc delete pvc -n {{ namespace }} {{ name }}"
  when: result is failed
- name: "PersistentVolumeClaim '{{ name }}'"
  when: result is failed
  k8s:
    state: present
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: "{{ name }}"
        namespace: "{{ namespace }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: slow
        selector:
          name: quay-redis


- name: "Create PVC '{{ name }}'"
  when: result is failed
  shell:
    cmd: |
      cat <<EOF | oc create -n "{{ namespace }}" -f -
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: "{{ name }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: slow
        selector:
          name: "{{ name }}"
      EOF
