---
- name: Create TLS cert and key
  tags: [start-setup, regenerate-certs]
  shell:
    cmd: |
      rm {{ volumes_dir }}/certs/*

      cp /etc/pki/tls/openssl.cnf {{ volumes_dir }}/certs/openssl.cnf
      cat <<EOF >> {{ volumes_dir }}/certs/openssl.cnf
      [ san ]
      subjectAltName="DNS: {{ quay_host }}:{{ quay_https_port }}"
      EOF

      # Root CA
      openssl genrsa -out {{ volumes_dir }}/certs/rootCA.key 4096
      openssl req -new -x509 \
          -key {{ volumes_dir }}/certs/rootCA.key \
          -out {{ volumes_dir }}/certs/rootCA.crt \
          -days 365 -extensions v3_ca -subj "/C=US/L=Syracuse/CN=Quay" \
          -config {{ volumes_dir }}/certs/openssl.cnf
      cat {{ volumes_dir }}/certs/rootCA.key {{ volumes_dir }}/certs/rootCA.crt | \
          tee {{ volumes_dir }}/certs/rootCA.pem

      # Quay server
      openssl genrsa -out {{ volumes_dir }}/certs/quay.key 4096
      openssl req -new \
          -key {{ volumes_dir }}/certs/quay.key \
          -out {{ volumes_dir }}/certs/quay.csr \
          -subj "/C=US/ST=New York/L=Cazenovia/O=Red Hat/OU=Quay/emailAddress=thomasmckay@redhat.com/CN={{ quay_host }}" \
          -config {{ volumes_dir }}/certs/openssl.cnf
      openssl x509 -req -days 365 \
          -in {{ volumes_dir }}/certs/quay.csr \
          -out {{ volumes_dir }}/certs/quay.crt \
          -CA {{ volumes_dir }}/certs/rootCA.crt -CAkey {{ volumes_dir }}/certs/rootCA.key \
          -CAcreateserial -extensions v3_req -extfile {{ volumes_dir }}/certs/openssl.cnf

      # Clair server
      openssl genrsa -out {{ volumes_dir }}/certs/clair.key 4096
      openssl req -new \
          -key {{ volumes_dir }}/certs/clair.key \
          -out {{ volumes_dir }}/certs/clair.csr \
          -subj "/C=US/ST=New York/L=Cazenovia/O=Red Hat/OU=Quay/emailAddress=thomasmckay@redhat.com/CN={{ quay_host }}" \
          -config {{ volumes_dir }}/certs/openssl.cnf
      openssl x509 -req -days 365 \
          -in {{ volumes_dir }}/certs/clair.csr \
          -out {{ volumes_dir }}/certs/clair.crt \
          -CA {{ volumes_dir }}/certs/rootCA.crt -CAkey {{ volumes_dir }}/certs/rootCA.key \
          -CAcreateserial -extensions v3_req -extfile {{ volumes_dir }}/certs/openssl.cnf

- name: Install rootCA
  tags: [start-setup]
  shell:
    cmd: |
      sudo cp {{ volumes_dir }}/certs/rootCA.crt /etc/pki/ca-trust/source/anchors
      sudo update-ca-trust extract
