---
- name: "Project {{ name }}"
  k8s:
    name: "{{ name }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Redis Service
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: quay-redis
        namespace: "{{ name }}"
        labels:
          app: "{{ name }}"
      spec:
        selector:
          name: quay-redis
        ports:
        - name: redis
          protocol: TCP
          targetPort: 6379
          port: 6379

- name: Postgresql Service
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: quay-postgresql
        namespace: "{{ name }}"
        labels:
          app: "{{ name }}"
      spec:
        selector:
          name: quay-postgresql
        ports:
        - name: postgresql
          protocol: TCP
          targetPort: 5432
          port: 5432


