---
#  psql "postgres://quay:quay@thomasmckay.usersys.redhat.com:5432/quay"
# Read-only https://access.redhat.com/articles/5411111

- name: quay postgresql - create volume
  tags: [aio-install]
  file:
    path: "{{ volumes_dir }}/{{ item }}"
    state: directory
    mode: "a+rwx"
  with_items:
    - quay-postgresql

- name: quay postgresql - start container
  tags: [aio-install, start-setup, restart-all, restart-postgresql]
  containers.podman.podman_container:
    name: quay-postgresql
    image: registry.redhat.io/rhscl/postgresql-96-rhel7:latest
    volumes:
      - "{{ volumes_dir }}/quay-postgresql:/var/lib/postgresql/data/pgdata:Z"
    env:
      POSTGRESQL_USER: quay
      POSTGRESQL_PASSWORD: quay
      POSTGRESQL_DATABASE: quay
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: quay
      POSTGRESQL_REPLICATION_PASSWORD: quay
    ports:
      - "5432:5432"
    rm: true
    state: started
    restart: true

- name: quay postgresql - add pg_trgm extension
  tags: [aio-install, start-setup, restart-all, restart-postgresql]
  shell:
    cmd: |
      podman exec quay-postgresql bash -l -c 'echo "CREATE EXTENSION pg_trgm" | psql quay'
  register: result
  until: result is succeeded
  retries: 5
  delay: 10

- name: Quay Postgresql Replica container
  tags: [restart-postgresql-replica]
  containers.podman.podman_container:
    name: quay-postgresql-replica
    image: registry.redhat.io/rhscl/postgresql-96-rhel7:latest
    volumes:
      - "{{ volumes_dir }}/quay-postgresql-replica:/var/lib/postgresql/data/pgdata:Z"
    env:
      POSTGRESQL_USER: quay
      POSTGRESQL_PASSWORD: quay
      POSTGRESQL_DATABASE: quay
      POSTGRESQL_MASTER_HOST: "{{ quay_host }}"
      POSTGRESQL_MASTER_PORT_NUMBER: "5432"
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: quay
      POSTGRESQL_REPLICATION_PASSWORD: quay
    ports:
      - "5434:5432"
    #keep_volumes: true
    #auto_remove: true
    rm: true
    state: started
    restart: true

- name: Postgresql add pg_trgm extension
  tags: [restart-postgresql-replica]
  shell:
    cmd: |
      podman exec quay-postgresql-replica bash -l -c 'echo "CREATE EXTENSION pg_trgm" | psql quay'
  register: result
  until: result is succeeded
  retries: 5
  delay: 10

- name: Clair Postgresql container
  tags: [start-setup, restart-all, restart-postgresql]
  containers.podman.podman_container:
    name: clair-postgresql
    image: registry.redhat.io/rhscl/postgresql-96-rhel7:latest
    volumes:
      - "{{ volumes_dir }}/clair-postgresql:/var/lib/postgresql/data/pgdata:Z"
    env:
      POSTGRESQL_USER: clair
      POSTGRESQL_PASSWORD: clair
      POSTGRESQL_DATABASE: clair
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: clair
      POSTGRESQL_REPLICATION_PASSWORD: clair
    ports:
      - "5433:5432"
    rm: true
    state: started
    restart: true

- name: Clair postgresql add uuid-ossp extension
  tags: [start-setup, restart-all, restart-postgresql]
  shell:
    cmd: |
      podman exec clair-postgresql bash -l -c 'echo "CREATE EXTENSION \"uuid-ossp\"" | psql clair'
  register: result
  until: result is succeeded
  retries: 5
  delay: 10


- name: quay postgresql - stop container
  tags: [aio-uninstall]
  ignore_errors: true
  shell:
    cmd: |
      podman kill {{ item }}
  with_items:
    - quay-postgresql


- name: quay postgresql - remove volume folder
  tags: [aio-uninstall]
  command: "sudo rm -Rf {{ volumes_dir }}/{{ item }}"
  args:
    removes: "{{ volumes_dir }}/{{ item }}"
  with_items:
    - quay-postgresql