---
- name: Quay Config container
  tags: [start-setup, restart-config]
  containers.podman.podman_container:
    name: quay-config
    image: "{{ quay_image }}"
    volumes:
      - "{{ volumes_dir }}/quay-config:/conf/stack:Z"
      - "/home/thomasmckay/code/quay-devel:/home/thomasmckay/code/quay-devel:Z"
    env:
      QUAYENTRY: config
      CONFIG_APP_PASSWORD: password
    ports:
      - "9080:8080"
      - "9443:8443"
    rm: true
    state: started
    restart: true
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
