---
- name: Quay Config container
  tags: [start-setup, restart-config]
  containers.podman.podman_container:
    name: quay-config
    image: "{{ quay_image }}"
    volumes:
      - "{{ volumes_dir }}/quay-config:/conf/stack:Z"
      - "/home/thomasmckay/code/quay-devel:/home/thomasmckay/code/quay-devel:Z"
      - "/home/thomasmckay/code/quay-devel/config-tool:/usr/local/bin/config-tool:Z"
    env:
      QUAYENTRY: config
      CONFIG_APP_PASSWORD: password
    ports:
      - "9080:8080"
      - "9443:8443"
    rm: true
    state: started
    restart: true
  register: result
  until: result is succeeded
  retries: 5
  delay: 10


- name: quay config - create volume folder
  tags: [aio-install]
  file:
    path: "{{ volumes_dir }}/{{ item }}"
    state: directory
    mode: "a+rwx"
  with_items:
    - quay-storage/local
    - quay-config/extra_ca_certs


- name: quay config - remove prior volume folder
  tags: [aio-uninstall]
  command: "sudo rm -Rf {{ volumes_dir }}/{{ item }}"
  args:
    removes: "{{ volumes_dir }}/{{ item }}"
  with_items:
    - quay-storage
    - quay-config


- name: quay config - create config bundle
  tags: [aio-install]
  vars:
    quay_endpoint: "{{ quay_host }}:8443"
  shell:
    cmd: |
      cp {{ volumes_dir }}/certs/rootCA.crt {{ volumes_dir }}/quay-config/extra_ca_certs/quay.crt
      cp {{ volumes_dir }}/certs/quay.crt {{ volumes_dir }}/quay-config/ssl.cert
      cp {{ volumes_dir }}/certs/quay.key {{ volumes_dir }}/quay-config/ssl.key
      chmod a+r -R {{ volumes_dir }}/quay-config

      cat <<EOF > {{ volumes_dir }}/quay-config/config.yaml
      ACTION_LOG_ARCHIVE_LOCATION: default
      ACTION_LOG_ARCHIVE_PATH: /datastorage/logs-archive
      ACTION_LOG_ROTATION_THRESHOLD: 2w
      ALLOW_PULLS_WITHOUT_STRICT_LOGGING: true
      AUTHENTICATION_TYPE: Database
      AVATAR_KIND: local
      BUILDLOGS_REDIS:
          host: quay.example.org
          port: 6379
      DATABASE_SECRET_KEY: 84127677-e5df-4ae6-861a-d27a87e28d01
      DB_CONNECTION_ARGS:
          autorollback: true
          threadlocals: true
      DB_URI: postgresql://quay:quay@quay.example.org/quay
      DEFAULT_TAG_EXPIRATION: 2w
      DISTRIBUTED_STORAGE_CONFIG:
          default:
            - LocalStorage
            - storage_path: /datastorage
      DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
      DISTRIBUTED_STORAGE_PREFERENCE:
        - default
      ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
      FEATURE_ACTION_LOG_ROTATION: true
      FEATURE_ANONYMOUS_ACCESS: true
      FEATURE_APP_SPECIFIC_TOKENS: false
      FEATURE_CHANGE_TAG_EXPIRATION: true
      FEATURE_DIRECT_LOGIN: true
      FEATURE_PARTIAL_USER_AUTOCOMPLETE: false
      FEATURE_USER_CREATION: true
      FEATURE_USER_LAST_ACCESSED: true
      FEATURE_USERNAME_CONFIRMATION: true
      FRESH_LOGIN_TIMEOUT: 10m
      GITHUB_LOGIN_CONFIG: {}
      GITHUB_TRIGGER_CONFIG: {}
      GITLAB_TRIGGER_KIND: {}
      LDAP_EMAIL_ATTR: mail
      LDAP_UID_ATTR: uid
      LDAP_URI: ldap://localhost
      LOGS_MODEL: database
      LOGS_MODEL_CONFIG: {}
      MAIL_DEFAULT_SENDER: support@quay.io
      MAIL_PORT: 587
      PREFERRED_URL_SCHEME: https
      REGISTRY_TITLE: Red Hat Quay
      REGISTRY_TITLE_SHORT: Red Hat Quay
      REPO_MIRROR_INTERVAL: 30
      REPO_MIRROR_TLS_VERIFY: true
      SEARCH_MAX_RESULT_PAGE_COUNT: 10
      SEARCH_RESULTS_PER_PAGE: 10
      SECURITY_SCANNER_INDEXING_INTERVAL: 30
      SERVER_HOSTNAME: quay.example.org:8443
      SETUP_COMPLETE: true
      SUPER_USERS:
        - admin
      TAG_EXPIRATION_OPTIONS:
        - 0s
        - 1d
        - 1w
        - 2w
        - 4w
      TEAM_RESYNC_STALE_TIME: 30m
      TESTING: false
      USER_EVENTS_REDIS:
          host: quay.example.org
          port: 6379
      USER_RECOVERY_TOKEN_LIFETIME: 30m

      EOF
