---
- name: Swagger container
  tags: [finish-setup, restart-all, restart-swagger]
  containers.podman.podman_container:
    name: swagger
    image:  swaggerapi/swagger-ui
    env:
      API_URL: "https://{{ quay_host }}:{{ quay_https_port }}/api/v1/discovery"
    ports:
      - "8888:8080"
    rm: true
    state: started
    restart: true
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
