# To setup clair on minishift
#
# ansible-playbook --private-key=~/.minishift/machines/minishift/id_rsa --u docker -i `minishift ip`, playbooks/clair-minishift.yaml
#
- hosts: all
  become: true
  tasks:
    - include: ../roles/minishift-volumes.yaml

- hosts: localhost
  vars:
    namespace: quay-enterprise
  tasks:
    - include: ../roles/clair.yaml
